name: Bug Report
description: Create a report to help us improve SwiftTemp
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to report a bug!
  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of the bug.
    validations:
      required: true
